[secrets]
# Git GPG signing key
gpg_signing_key = "op://ciqvg4fp2qwkc7eqtx2hy2ugeu/liy3lxepjn6z6kjv5kab55iism/signingkey"

# Example API keys and credentials (replace with your actual 1Password references)
# openai_api_key = "op://Private/OpenAI API Key/credential"
# github_token = "op://Private/GitHub Personal Access Token/credential"  
# aws_access_key_id = "op://Private/AWS Credentials/username"
# aws_secret_access_key = "op://Private/AWS Credentials/password"
# anthropic_api_key = "op://Private/Anthropic API Key/credential"
# docker_username = "op://Private/Docker Hub/username"
# docker_password = "op://Private/Docker Hub/password"
# npm_token = "op://Private/NPM Token/credential"
