[packages.curl]
packages = ["zsh"]

# [packages.apt]
# to_remove = ["btop", "htop"]
# [packages.apt.common]
# packages = [
#     "apt-transport-https",
#     "bat",                 # cat with syntax highlighting and Git integration
#     "curl",
#     "dnsutils",
#     "fd-find",
#     "figlet",
#     "fzf",
#     "git",
#     "git-extras",
#     "gnupg",
#     "gpg",
#     "jq",
#     "logrotate",
#     "lolcat",
#     "mc",                  # Midnight Commander
#     "nano",
#     "ncdu",                # NCurses Disk Usage
#     "needrestart",
#     "net-tools",
#     "openssh-server",
#     "p7zip-full",
#     "ripgrep",             # search tool like grep and the silver searcher
#     "sudo",
#     "tzdata",
#     "unzip",
#     "wget",
#     "zsh",
# ]
#
# [packages.python]
# to_remove = []
# [packages.python.common]
# packages = ["halper", "pygments"]
# [packages.python.dev_computer]
# packages = ["ansible-core", "cookiecutter", "poetry"]
# [packages.python.homelab_member]
# # 'GITEA_ADDRESS' is overwritten by the 'gitea_address' secret
# packages = ["git+GITEA_ADDRESS/natelandau/usrbin"]
# [packages.python.personal_computer]
# packages = ["vid-cleaner"]

[packages.homebrew]
to_remove = ["lingo-x"]
[packages.homebrew.common]
taps = ["oven-sh/bun"]
casks = [
    "zed",                 # IDE
    "font-jetbrains-mono", # JetBrains Mono font
    "ghostty",             # Terminal emulator
    "orbstack",            # Docker replacement
    "bruno",               # IDE for testing APis
    "beekeeper-studio",    # Database management tool
    "arc",                 # Browser
    "obsidian",            # Markdown Editor
    "raycast",             # Launcher
    "figma",               # Design tool
    "spotify",             # Music player
    "notion-calendar",     # Calendar app
    "github",              # Github GUI
    "todoist",             # Task management tool
]
formulae = [
    "atuin",         # Better shell history
    "chezmoi",       # Dotfile manager
    "fzf",           # Fuzzy finder
    "git",           # Git version control system
    "openssl",       # SSL/TLS cryptography library
    "rip2",          # A safer, rust-based rm
    "tree",          # Display directories as trees (with optional color/HTML output)
    "zoxide",        # A faster way to navigate your filesystem
    "zsh",           # Z shell
    "gh",            # GitHub CLI
    "git-workspace", # Git workspace management tool
    "duti",

    # Typescript Tools
    "nvm", # Node Version Manager
]
[packages.homebrew.work_computer]
casks = [
    "firefox",       # Browser
    "google-chrome", # Browser
]
formulae = []
[packages.homebrew.personal_computer]
to_remove = ["bitwarden"]
casks = [
    "tailscale",     # VPN for NAS
    "mullvadvpn",    # VPN
    "google-chrome", #Browser
    "iina",          # Video Pleayer
    "kap",           # Screen recorder
    "lulu",          # Firewall
    "plex",          # Movie Streamer
    "qbittorrent",   # Torrent client
    "raindropio",    # Bookmark manager
    # "roon",        # Music streaming service (Nas)
    "1password",     # Password Manager (GUI)
    "1password-cli", # Password Manager (CLI)

]
formulae = []

[packages.mas]
[packages.mas.common]
apps = []
[packages.mas.dev_computer]
apps = []
[packages.mas.homelab_member]
apps = []
[packages.mas.personal_computer]
apps = []
