[packages.curl]
packages = ["zsh"]

[packages.homebrew]
to_remove = [
    "lingo-x",
    "zoxide",
    "zsh-autosuggestions",
    "zsh-autocomplete",
    "duti",
]
[packages.homebrew.common]
taps = ["oven-sh/bun"]
casks = [
    "zed",                 # IDE
    "font-jetbrains-mono", # JetBrains Mono font
    "ghostty",             # Terminal emulator
    "orbstack",            # Docker replacement
    "bruno",               # IDE for testing APis
    "beekeeper-studio",    # Database management tool
    "arc",                 # Browser
    "obsidian",            # Markdown Editor
    "raycast",             # Launcher
    "figma",               # Design tool
    "spotify",             # Music player
    "notion-calendar",     # Calendar app
    "github",              # Github GUI
    "todoist",             # Task management tool
    "claude",              # claude Desktop
]
formulae = [
    "atuin",         # Better shell history
    "chezmoi",       # Dotfile manager
    "fzf",           # Fuzzy finder
    "git",           # Git version control system
    "openssl",       # SSL/TLS cryptography library
    "rip2",          # A safer, rust-based rm
    "tree",          # Display directories as trees (with optional color/HTML output)
    "zsh",           # Z shell
    "gh",            # GitHub CLI
    "git-workspace", # Git workspace management tool
    "ripgrep",
    "powerlevel10k",


    # Typescript Tools
    "nvm", # Node Version Manager
]
[packages.homebrew.work_computer]
casks = [
    "firefox",       # Browser
    "google-chrome", # Browser
]
formulae = []
[packages.homebrew.personal_computer]
to_remove = ["bitwarden", "mullvadvpn", "lulu", "kap"]
casks = [
    "tailscale",     # VPN for NAS
    "mullvad-vpn",   # VPN
    "google-chrome", #Browser
    "iina",          # Video Pleayer
    "plex",          # Movie Streamer
    "qbittorrent",   # Torrent client
    "raindropio",    # Bookmark manager
    # "roon",        # Music streaming service (Nas)
    "1password",     # Password Manager (GUI)
    "1password-cli", # Password Manager (CLI)

]
formulae = []

[packages.npm]
[packages.npm.common]
packages = [
    "@anthropic-ai/claude-code", # Claude Code CLI
]
[packages.npm.work_computer]
packages = []
[packages.npm.personal_computer]
packages = []

[packages.mas]
[packages.mas.common]
apps = []
[packages.mas.dev_computer]
apps = []
